version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: order-postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: order-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: orders
      RABBITMQ_DEFAULT_PASS: orders
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - order-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  order-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: