quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=orders
quarkus.datasource.password=orders
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/orders
quarkus.datasource.jdbc.max-size=100
quarkus.datasource.jdbc.min-size=50

quarkus.hibernate-orm.log.sql=false

quarkus.flyway.locations=db/migration
quarkus.flyway.migrate-at-start=true

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=orders
rabbitmq-password=orders


mp.messaging.outgoing.order-created.connector=smallrye-rabbitmq
mp.messaging.outgoing.order-created.exchange.name=order.events
mp.messaging.outgoing.order-created.routing-key=order.created

mp.messaging.incoming.order-created-consumer.connector=smallrye-rabbitmq
mp.messaging.incoming.order-created-consumer.queue.name=order.created.queue
mp.messaging.incoming.order-created-consumer.exchange.name=order.events
mp.messaging.incoming.order-created-consumer.routing-key=order.created

# Outbox Poller configuration
outbox.poll.interval=500ms
outbox.poll.batch-size=200
outbox.retry.max=10
